server:
  rootPath: /api/*
  applicationConnectors:
       - type: http
         port: 8080
#         keyStorePath: moves.keystore
#         keyStorePassword: movescelebrity


postgres:
  host: jdbc:postgresql://ec2-174-129-229-106.compute-1.amazonaws.com
  databaseName: de91vgmhqf63dk
  port: 5432
  user: jbfmhssxeimhbv
  password: 94187571cb4de0c1feac57ef54683254bedb40230f4d5d20394ee3733b7f068d